databases:
  - name: ferrybook
    databaseName: ferrybook
    user: Ferry Books
    region: singapore

services:
  - type: web
    name: Ferry Books
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ferrybook
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false